### ISSUE TITLE
`findComponent` doesn't work as expected on <Text> components.

### ISSUE THREAD

**Issue by sdroadie** [pixielabs/cavy#101]
According to the README.md, `<Text>` components should be inspectable using `findComponent`, and I've been unable to do this. In the following example spec:

```js
export default (spec) => {
  spec.describe('Test', () => {
    spec.it('works', async () => {
      await spec.fillIn('Test.Input', 'test');
      const text = await spec.findComponent('Test.Text');
      await containsText(text, 'test');
    })
  })
}
```

Assume here that `Test.Input` and `Test.Text` exist, that filling in `Test.Input` sets the text in `Test.Text`, and that `containsText` matches the example in the README.md. When this test is run, it returns an error, logging `Cannot read property 'children' of undefined`. It looks like `findComponent` isn't returning what is expected.

This is on React Native 0.56.

**Comment by AbigailMcP** [comment]
Hi @sdroadie !

`findComponent` will return the specified component if found. You should then be able to call `props` on your component and call any of the props if they are functions / check their values.

I just tried out a quick example using React Native 0.57 and can't see any issues...

With a hooked up `TextInput` component I tweaked the `containsText` function to check the `value` prop as follows, and the test passes:

```
export async function containsText(component, text) {
  if (!component.props.value.includes(text)) {
    throw new Error(`Could not find text ${text}`);
  };
}
```

I'm closing this issue for now as I can't replicate, but please let me know if this is still an issue and I'll try to help further (as @Rafael-Martins said, a log of your text variable would be useful)

**Comment by funador** [comment]
Hi @AbigailMcP! I am having a similar issue with `Cannot read property 'children' of undefined` with 0.59.9

```js
// spec
const nameFeedback = await spec.findComponent('Text.Name');
console.log('nameFeedback', nameFeedback);
```

```js
// helper
const containsText = async (component, text) => {
  if (!component.props.children.includes(text)) {
    throw new Error(`Could not find text ${text}`);
  }
};
```

```js
// component
<Text style={hasError} ref={useCavy()('Text.Name')}>
  {message}
</Text>
```


Here is the log:
```
ReactNativeFiberHostComponent {_nativeTag: 2565, _children: Array(1), viewConfig: {…}}
  viewConfig:
  directEventTypes: {topTextLayout: {…}}
  uiViewClassName: "RCTText"
  validAttributes: {pointerEvents: true, accessible: true, accessibilityActions: true, accessibilityLabel: true, accessibilityComponentType: true, …}
  __proto__: Object
_children: Array(1)
  0: 2563
  length: 1
  __proto__: Array(0)
_nativeTag: 2565
__proto__: Object
```

Also tried with `value` as suggested in the comment above. Appreciate any insight you can provide.
