### ISSUE TITLE
Can't build proyect with travis Ci

### ISSUE THREAD

**Issue by AlanGDC** [pixielabs/cavy#116]
Hi! Im having a problem trying to implement Cavy to our ci mobile project, we are using travis, after its starts "cavi-cli" its get freeze and after a long time (like 10 minutes), travis terminate the build for a time out kind of message:
```shell
...
▸ Build Succeeded

The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
	Analyze RCTNetInfo.m normal x86_64
(2 commands with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/[secure]-platform-app.app
Launching ar.com.[secure].platform
ar.com.[secure].platform: 57420
cavy: react-native exited with code 0.
cavy: listening on port 8082 for test results...
::1 - - [29/Mar/2019:19:19:33 +0000] "GET /index.bundle?platform=ios&dev=true&minify=false HTTP/1.1" 200 - "-" "[secure]-platform-app/6 CFNetwork/897.15 Darwin/17.7.0"
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1536/1536), done.


_No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated_
```

This is my .travis.yml:
```
jobs:
  include:
     - stage: Test Automation E2E ✅
       if: branch = feature/automation AND type = push
       os: osx
       osx_image: xcode10.1
       node_js: 10
       cache:
         yarn: true
         directories:
           - node_modules
       before_install:
           - curl -o- -L https://yarnpkg.com/install.sh | bash
           - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"    
           - gem install cocoapods --pre
           - brew install watchman 
       install:           
          - yarn global add cavy-cli
          - yarn global add react-native-cli
          - yarn install --network-concurrency 1
          - cd ios && pod install --repo-update && cd ..
       script:
         - watchman watch-del-all
         - react-native start --reset-cache
         - cavy run-ios


```

Can you help us with this issue or have some look a like configuration for travis that we can use? Thanks a lot!

**Comment by jalada** [comment]
Hi @AlanGDC, we've not tried cavy-cli in Travis.  The lack of output suggests the app is either not booting (due to an error), or it's taking too long to start, or Cavy isn't set up to report test results to Cavy CLI.

It _looks_ like your app is booting OK because it looks like it's downloading your index.js. Have you set up Cavy to report tests to Cavy CLI (using `sendReport={true}` as per https://github.com/pixielabs/cavy-cli#installation)? Does `cavy run-ios` work on your own machine?

**Comment by AlanGDC** [comment]
Hi! @jalada, no i haven't set up Cavy to report test but i'll do it for now on, and yes! its works just fine and well:
```shell 
▸ Build Succeeded

The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
	Analyze RCTNetInfo.m normal x86_64
(2 commands with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/iunigo-platform-app.app
Launching ar.com.iunigo.platform
ar.com.iunigo.platform: 7339
cavy: react-native exited with code 0.
cavy: listening on port 8082 for test results...
1) Authentication Feature: Scenario: Login OK and Log Out  ✅
Finished in 7.341 seconds
1 example, 0 failures
```

**Comment by AbigailMcP** [comment]
Nice one @jalada :) closing this issue.
Let us know if you have any further issues @AlanGDC !

**Comment by AlanGDC** [comment]
Wait! Sorry @AbigailMcP, i don't think the issue is closed jaja, i have all ready configure the test-reports for cavy-cli, but im sill can't get it to run in travis ci , i will try to run it with the SampleApp that you have, but till i get it work i don't think this should be closed, thanks!

**Comment by AbigailMcP** [comment]
Ooops sorry @AlanGDC, my bad! Re-opened :)

**Comment by AlanGDC** [comment]
Finally build it !
I share my travis.yml for you and anyone trying this:
```
   os: osx
       osx_image: xcode10.1
       node_js: 10
       cache:
         yarn: true
         directories:
           - node_modules
       before_install:
           - curl -o- -L https://yarnpkg.com/install.sh | bash
           - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"    
           - gem install cocoapods --pre
       install:           
          - yarn global add cavy-cli
          - yarn global add react-native-cli
          - yarn install 
       script:
         - react-native start --reset-cache &
         - cavy run-ios
```
But also i must say that wasn't easy to build your sample app; i was having some troubles get it to work cause i was getting the message "navigator react native deprecated", so i imported from "react-native-deprecated-custom-components' and then it works fine.
Thanks a lot!! Awesome tool!
